using System;

namespace Plexure.Sample.Models
{

    /// <summary>
    /// Exercise 2:
    /// A coupon management system stores a definition of a coupon and also every time a user redeems a coupon.
    /// A coupon consists of an id, a title, a start date, end date, maximum number of coupons per user and also a maximum number of coupons across all users.
    /// When a user redeems a coupon the system keeps track of the users identifier, the datetime when the redemption occurred and a unique code that is generated by the application.
    /// </summary>
    public class Coupon
    {
        public int Id { get; set; }

        public DateTime CreatedOnUtc { get; set; }

        public DateTime ModifiedOnUtc { get; set; }

        public DateTime EndDateUtc { get; set; }

        public bool IsActive { get; set; }

        public long MaxAllocation { get; set; }

        public int MaxUserAllocation { get; set; }

        public DateTime StartDateUtc { get; set; }

        public string Title { get; set; }

        public long TotalRedemptions { get; set; }

    }

    public class CouponRedemption
    {
        public long Id { get; set; }

        public int CouponId { get; set; }

        public int UserId { get; set; }

        public DateTime CreatedOnUtc { get; set; }

        public DateTime ModifiedOnUtc { get; set; }

        public Guid ApplicationIdentifier { get; set; }

        public DateTime RedemtionDateUtc { get; set; }

    }

    public class UserCouponRedemption
    {
        public int CouponId { get; set; }

        public int UserId { get; set; }

        public DateTime CreatedOnUtc { get; set; }

        public DateTime ModifiedOnUtc { get; set; }

        public int TotalRedemptions { get; set; }

    }
}

/*
Using MS SQL

Coupon
Optimisation 
- Index on the Coupon.Id
- Index on the Coupon.IsActive

Depending on 

CouponRedemption
Index on CouponRedemption.CouponId and CouponRedemption.UserId
Index on ApplicationIdentifier

UserCouponRedemption
Index on UserCouponRedemption.CouponId and UserCouponRedemption.UserId

 */
